---
- name: Install OpenJDK 11 on Ubuntu
  hosts: slave
  become: true
  become_method: sudo
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present
